CREATE TABLE llx_navinvoice_invoice (
    rowid integer AUTO_INCREMENT PRIMARY KEY,
    entity integer NOT NULL DEFAULT 1,
    invoice_direction varchar(8) NOT NULL DEFAULT 'OUTBOUND',
    invoice_number varchar(50) NOT NULL,
    batch_index integer NOT NULL DEFAULT 0,
    invoice_operation varchar(16) NULL,
    invoice_category varchar(16) NULL,
    invoice_issue_date date NULL,
    supplier_tax_number varchar(20) NULL,
    supplier_name varchar(512) NULL,
    customer_tax_number varchar(20) NULL,
    customer_name varchar(512) NULL,
    payment_method varchar(32) NULL,
    payment_date date NULL,
    invoice_appearance varchar(32) NULL,
    source varchar(16) NULL,
    invoice_delivery_date date NULL,
    currency varchar(3) NULL,
    invoice_net_amount decimal(24,8) NULL,
    invoice_net_amount_huf decimal(24,8) NULL,
    invoice_vat_amount decimal(24,8) NULL,
    invoice_vat_amount_huf decimal(24,8) NULL,
    transaction_id varchar(64) NULL,
    transaction_index integer NULL,
    original_invoice_number varchar(50) NULL,
    modification_index integer NULL,
    ins_date datetime NULL,
    completeness_indicator smallint NOT NULL DEFAULT 0,
    raw_digest mediumtext NULL,
    digest_hash varchar(64) NULL,
    invoice_data longtext NULL,
    data_hash varchar(64) NULL,
    data_fetched smallint NOT NULL DEFAULT 0,
    fk_facture integer NULL,
    fk_facture_fourn integer NULL,
    datec datetime NOT NULL,
    tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    last_sync datetime NULL
) ENGINE=innodb;
